name: Daily Avocado Check

on:
  schedule:
    # Run at 8:00 AM UTC (10:00 AM EET)
    - cron: '0 8 * * *'
  # Allow manual triggering for testing
  workflow_dispatch:

jobs:
  check-avocado:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run avocado stock check
      env:
        RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
      run: node check-once.js 